### ISSUE TITLE
Action fails during gigalixir login step with pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by ryoung786** [mhanberg/gigalixir-action#19]
My deploys have started failing during the login step with this error in the logs: `pkg_resources.DistributionNotFound: The 'pyOpenSSL>=0.14; extra == "security"' distribution was not found and is required by requests`.

My last successful action ran on Nov 1, using `v0.2.1`.  I have bumped it up to `v0.4.0` but still see the same error.  I haven't made any other changes to my workflow file in between now (Nov 15) and then.

Thanks so much for creating this action - it's made for a great CI/CD workflow for my project!

**Raw Logs:**
```
2020-11-15T19:23:40.1969520Z ##[group]Run mhanberg/gigalixir-action@v0.4.0
2020-11-15T19:23:40.1970542Z with:
2020-11-15T19:23:40.1971940Z   GIGALIXIR_USERNAME: ***
2020-11-15T19:23:40.1972841Z   GIGALIXIR_PASSWORD: ***
2020-11-15T19:23:40.1973714Z   GIGALIXIR_APP: ***
2020-11-15T19:23:40.2021549Z   SSH_PRIVATE_KEY: ***

2020-11-15T19:23:40.2022213Z   MIGRATIONS: false
2020-11-15T19:23:40.2022857Z ##[endgroup]
2020-11-15T19:23:40.2448296Z ##[group]Installing gigalixir
2020-11-15T19:23:40.2509023Z [command]/usr/bin/sudo pip install gigalixir --ignore-installed six
2020-11-15T19:23:43.1397979Z The directory '/home/runner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
2020-11-15T19:23:43.1401374Z The directory '/home/runner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
2020-11-15T19:23:43.1431545Z Collecting gigalixir
2020-11-15T19:23:43.2936859Z   Downloading https://files.pythonhosted.org/packages/0d/58/76772c006992ac094791e6d42f14410eacac88a5a19b16bd5073fa2beb67/gigalixir-1.2.1.tar.gz
2020-11-15T19:23:44.2911289Z Collecting six
2020-11-15T19:23:44.3382838Z   Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
2020-11-15T19:23:44.3416896Z Collecting click>=6.7 (from gigalixir)
2020-11-15T19:23:44.3920091Z   Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
2020-11-15T19:23:44.4101555Z Collecting pygments>=2.2.0 (from gigalixir)
2020-11-15T19:23:44.4753279Z   Downloading https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl (896kB)
2020-11-15T19:23:44.6395489Z Collecting qrcode>=6.1 (from gigalixir)
2020-11-15T19:23:44.6787161Z   Downloading https://files.pythonhosted.org/packages/42/87/4a3a77e59ab7493d64da1f69bf1c2e899a4cf81e51b2baa855e8cc8115be/qrcode-6.1-py2.py3-none-any.whl
2020-11-15T19:23:44.6952237Z Collecting requests>=2.20.0 (from gigalixir)
2020-11-15T19:23:44.7967274Z   Downloading https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl (61kB)
2020-11-15T19:23:44.8147284Z Collecting rollbar>=0.13.11 (from gigalixir)
2020-11-15T19:23:44.9571611Z   Downloading https://files.pythonhosted.org/packages/03/b4/43f2ffb3678d6a16a76b24c5a05c3c727dad50b23808f3e4ddc938a8ac1f/rollbar-0.15.1.tar.gz (48kB)
2020-11-15T19:23:45.1298299Z Collecting stripe>=1.28.0 (from gigalixir)
2020-11-15T19:23:45.3135397Z   Downloading https://files.pythonhosted.org/packages/6c/d0/10fb088453ebe5ab40b940d39022a88bddf86e11fc9f137d36298aafc536/stripe-2.55.0-py2.py3-none-any.whl (204kB)
2020-11-15T19:23:45.3508453Z Collecting chardet<4,>=3.0.2 (from requests>=2.20.0->gigalixir)
2020-11-15T19:23:45.3845606Z   Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
2020-11-15T19:23:45.4035554Z Collecting certifi>=2017.4.17 (from requests>=2.20.0->gigalixir)
2020-11-15T19:23:45.4550339Z   Downloading https://files.pythonhosted.org/packages/c1/6f/3d85f0850962279a7e4c622695d7b3171e95ac65308a57d3b29738b27149/certifi-2020.11.8-py2.py3-none-any.whl (155kB)
2020-11-15T19:23:45.4752811Z Collecting urllib3<1.27,>=1.21.1 (from requests>=2.20.0->gigalixir)
2020-11-15T19:23:45.5469076Z   Downloading https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl (136kB)
2020-11-15T19:23:45.5761979Z Collecting idna<3,>=2.5 (from requests>=2.20.0->gigalixir)
2020-11-15T19:23:45.6130076Z   Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
2020-11-15T19:23:45.6214327Z Installing collected packages: click, pygments, six, qrcode, chardet, certifi, urllib3, idna, requests, rollbar, stripe, gigalixir
2020-11-15T19:23:46.3153653Z   Running setup.py install for rollbar: started
2020-11-15T19:23:46.5214993Z     Running setup.py install for rollbar: finished with status 'done'
2020-11-15T19:23:46.5921012Z   Running setup.py install for gigalixir: started
2020-11-15T19:23:46.8141100Z     Running setup.py install for gigalixir: finished with status 'done'
2020-11-15T19:23:46.8579881Z Successfully installed certifi-2020.11.8 chardet-3.0.4 click-7.1.2 gigalixir-1.2.1 idna-2.10 pygments-2.5.2 qrcode-6.1 requests-2.25.0 rollbar-0.15.1 six-1.15.0 stripe-2.55.0 urllib3-1.26.2
2020-11-15T19:23:46.9165334Z ##[endgroup]
2020-11-15T19:23:46.9174351Z ##[group]Logging in to gigalixir
2020-11-15T19:23:46.9193457Z [command]/usr/local/bin/gigalixir login -e *** -y -p ***
2020-11-15T19:23:47.0471005Z Traceback (most recent call last):
2020-11-15T19:23:47.0534574Z   File "/usr/local/bin/gigalixir", line 6, in <module>
2020-11-15T19:23:47.0536634Z     from pkg_resources import load_entry_point
2020-11-15T19:23:47.0539934Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
2020-11-15T19:23:47.0763150Z     @_call_aside
2020-11-15T19:23:47.0768214Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
2020-11-15T19:23:47.0769783Z     f(*args, **kwargs)
2020-11-15T19:23:47.0771739Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
2020-11-15T19:23:47.0784276Z     working_set = WorkingSet._build_master()
2020-11-15T19:23:47.0787722Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
2020-11-15T19:23:47.0789264Z     ws.require(__requires__)
2020-11-15T19:23:47.0790930Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
2020-11-15T19:23:47.0792591Z     needed = self.resolve(parse_requirements(requirements))
2020-11-15T19:23:47.0794483Z   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
2020-11-15T19:23:47.0796131Z     raise DistributionNotFound(req, requirers)
2020-11-15T19:23:47.0798602Z pkg_resources.DistributionNotFound: The 'pyOpenSSL>=0.14; extra == "security"' distribution was not found and is required by requests
2020-11-15T19:23:47.0910689Z ##[endgroup]
2020-11-15T19:23:47.0916682Z ##[error]The process '/usr/local/bin/gigalixir' failed with exit code 1
```

**Relevent section of Workflow File:**
```
  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch

      - uses: mhanberg/gigalixir-action@v0.4.0
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIGRATIONS: false  # defaults to true
```

**Comment by jesseshieh** [comment]
If I had to guess, I'd say this is somehow related to this, although I haven't dug into it yet.
https://github.com/gigalixir/gigalixir-cli/pull/72

For now, I'll add pyOpenSSL in the `install_requires` and see if that fixes this. It seemed to help a similar situation I found here
https://github.com/splunk/eventgen/issues/96

**Comment by jesseshieh** [comment]
Just added
https://github.com/gigalixir/gigalixir-cli/commit/c01cc452839443ffc48267fc682b93a91cf048d7

And deployed as v1.2.2. Can you re-run and see if that helped?
For what it's worth, I can't seem to reproduce this locally with python3. Perhaps this is a python2.7 issue?

**Comment by ryoung786** [comment]
That did the trick, thank you!

**Comment by mhanberg** [comment]
Thanks @jesseshieh!!
