### ISSUE TITLE
Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by AkhileshNegi** [mhanberg/gigalixir-action#24]
Hi, I'm getting the following error when trying to deploy with new tagv0.4.2

Run mhanberg/gigalixir-action@v0.4.2

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.833 (/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:157:33)
    at __nccwpck_require__ (/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:199:42)
    at Object.842 (/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:8:14)
    at __nccwpck_require__ (/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:199:42)
    at /home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:216:18
    at Object.<anonymous> (/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js:217:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/mhanberg/gigalixir-action/v0.4.2/dist/index.js'
  ]
}

```

**Comment by mhanberg** [comment]
For some reason the build was not generated correctly 😭, I think I've fixed it

**Comment by mhanberg** [comment]
Please try v0.4.3

**Comment by AkhileshNegi** [comment]
@mhanberg I tried with tag 0.4.3, there is still some errors.
```
Run mhanberg/gigalixir-action@v0.4.3
Installing gigalixir
  /usr/bin/pip3 install gigalixir
  Collecting gigalixir
    Downloading https://files.pythonhosted.org/packages/66/98/c698c1577d1f3aec71a71df51af39547aace3a79f3e5c724ab203cd9a542/gigalixir-1.2.2.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'setuptools'
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c7f1hsnu/gigalixir/
Error: The process '/usr/bin/pip3' failed with exit code 1
```

**Comment by mhanberg** [comment]
Can you try adding the Python action as mentioned here: https://github.com/mhanberg/gigalixir-action/pull/23#issuecomment-779473187

**Comment by AkhileshNegi** [comment]
@mhanberg Thanks. that did the trick🎉🎉. I am closing the issue
