### ISSUE TITLE
Python error: 'Command "python setup.py egg_info" failed with error code 1'

### ISSUE THREAD

**Issue by henrik** [mhanberg/gigalixir-action#31]
Please see: https://github.com/henrik/qed/runs/2106042247?check_suite_focus=true

This is what my ci.yml looked like at that point: https://github.com/henrik/qed/blob/1ab951dd94b420d082ce7c8c77b4b3b48718cc39/.github/workflows/ci.yml

```
Run mhanberg/gigalixir-action@v0.4.0
  with:
    GIGALIXIR_USERNAME: ***
    GIGALIXIR_PASSWORD: ***
    GIGALIXIR_APP: qed
    SSH_PRIVATE_KEY: ***
  
    MIGRATIONS: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.1/x64/lib
Installing gigalixir
  /usr/bin/sudo pip install gigalixir --ignore-installed six
  The directory '/home/runner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  The directory '/home/runner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting gigalixir
    Downloading https://files.pythonhosted.org/packages/c5/88/f83e5d3d1ecc2354c3b523e5fc0c7f6625e912889ca28e5bdca66a69af43/gigalixir-1.2.3.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-0GzfnZ/gigalixir/setup.py", line 41, in <module>
          'sure',
        File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
          replace_conflicting=True,
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
          replace_conflicting=replace_conflicting
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
          return installer(requirement)
        File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
          return cmd.easy_install(req)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1165, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0GzfnZ/gigalixir/
Error: The process '/usr/bin/sudo' failed with exit code 1
```

**Comment by mhanberg** [comment]
Are you still seeing this?

**Comment by henrik** [comment]
Hi @mhanberg!

Just tried restoring the Gigalixir step and bumped this action to 0.4.3: https://github.com/henrik/qed/commit/f48d5a89eb9b628fa3110b53b63699537cf3dc6a

And now it does appear to work! https://github.com/henrik/qed/runs/2426643622

Great – closing the ticket.
