### ISSUE TITLE
gigalixir-action fails on missing 'six' Python lib

### ISSUE THREAD

**Issue by hubertlepicki** [mhanberg/gigalixir-action#58]
Hey there,

2 days ago, when I did the last release of the app, gigalixir-action@0.6.2 did output the following libraries that installed:

```
certifi-2023.7.22 cffi-1.16.0 charset-normalizer-3.3.2 click-8.1.7 cryptography-41.0.5 gigalixir-1.9.0 idna-3.4 pyOpenSSL-23.3.0 pycparser-2.21 pygments-2.16.1 pypng-0.20220715.0 qrcode-7.4.2 requests-2.31.0 rollbar-0.16.3 six-1.16.0 stripe-7.4.0 typing-extensions-4.8.0 urllib3-2.1.0
```

Today, it installed:

```
certifi-2023.7.22 cffi-1.16.0 charset-normalizer-3.3.2 click-8.1.7 cryptography-41.0.5 gigalixir-1.9.0 idna-3.4 pyOpenSSL-23.3.0 pycparser-2.21 pygments-2.16.1 pypng-0.20220715.0 qrcode-7.4.2 requests-2.31.0 rollbar-1.0.0 stripe-7.5.0 typing-extensions-4.8.0 urllib3-2.1.0
```

The result is that since today, the 'six' library is missing and Gigalixir action fails on trying to login:

```
Logging in to gigalixir
  /opt/hostedtoolcache/Python/3.8.1/x64/bin/gigalixir login -e *** -y -p ***
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.1/x64/bin/gigalixir", line 5, in <module>
      from gigalixir import cli
    File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/gigalixir/__init__.py", line 8, in <module>
      from . import observer as gigalixir_observer
    File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/gigalixir/observer.py", line 13, in <module>
      from . import app as gigalixir_app
    File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/gigalixir/app.py", line 13, in <module>
      from . import presenter
    File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/gigalixir/presenter.py", line 6, in <module>
      from six import u as unicode
  ModuleNotFoundError: No module named 'six'
Error: The process '/opt/hostedtoolcache/Python/3.8.1/x64/bin/gigalixir' failed with exit code 1
```

I have fixed the issue for  myself, by installing the missing library in my yaml file:

```
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.1

      - run: pip3 install six

      - uses: gigalixir/gigalixir-action@v0.6.2
        with:
          ...
```

but it probably is because rollbar updated and you probably need to explicitly depend on the 'six' library, or something like that :)

All the best and Happy Friday!

**Comment by hubertlepicki** [comment]
It's probably this issue: https://github.com/gigalixir/gigalixir-cli/issues/80

I don't know anything about Python dependency management but I suspect the best way is to lock the dependency versions, if possible, so that they don't break?
